spring:
  application:
    name: proxy-service

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    customer:
      path: /customer/**
      serviceId: customer-service
      #serviceId should correspond to application name of each micro service
      #which is defined at specific application.properties file as “spring.application.name” property

ribbon:
  eureka:
    enabled: true
    # by default this is true. If false, cannot access customer-service via proxy-service
